version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fsadmin
      POSTGRES_PASSWORD: fssecret
      POSTGRES_DB: fsapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
    environment:
      DATABASE_URL: postgres://fsadmin:fssecret@db:5432/fsapp
    ports:
      - "4000:4000"
    depends_on:
      - db

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data: